name: Deployment Exercise 1
on: push
jobs: 
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          cd 04_Practice_Project
          npm ci
      - name: Lint
        run: |
          cd 04_Practice_Project
          npm run lint
      - name: Test code
        run: |
          cd 04_Practice_Project 
          npm run test
      - name: Build code
        run: |
          cd 04_Practice_Project
          npm run build
      - name: Deploy code
        run: echo "Deploying..."
